# Generated by Django 3.2.25 on 2024-07-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='artworks.artwork')),
            ],
        ),
    ]
